[phases.setup]
nixPkgs = ['...', 'taglib']
nixLibs = ['...', 'taglib']

[phases.install]
nixPkgs = ['...', 'taglib']
nixLibs = ['...', 'taglib']

[phases.build]
nixPkgs = ['...', 'taglib']
nixLibs = ['...', 'taglib']
